### ISSUE TITLE
How can i use LLM for sentnece correction ..

### ISSUE THREAD

**Issue by ShadowVicky** [rajshah4/snowflake-notebooks#3]
How can i use LLM for sentences correction? For this dataset
https://www.comp.nus.edu.sg/~nlp/corpora.html

here is the dataset link.. Only for the ENGLISH LANGUAGE..
EXAMPLE:: SUPPOSE I HVAE sentence like:
U wan me to "chop" seat 4 u nt?

I HAVE TO MAKE IT LIKE::
Do you want me to reserve seat for you or not?

**Comment by rajshah4** [comment]
In the old days, you would fine/tune or train a language model on examples like what you are showing. There are probably datasets like that on Hugging Face.  
But nowadays, you can just ask a LLM directly to convert the sentence into a professional tone with a prompt.  That is the simplest way.
